apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - configmap.yaml
  - podmonitor.yaml
  - trigger-authentication.yaml
  - scaledobject.yaml
  # Service is created by the Skupper Listener (host: banking-service).
  # Credentials: ExternalSecret banking-service-db
commonLabels:
  app.kubernetes.io/name: banking-service
  app.kubernetes.io/part-of: banking-si-demo
  app.kubernetes.io/component: backend
