apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: east
spec:
  provider:
    vault:
      server: http://vault.banking-vault.svc:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: banking-eso
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
