apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: banking-service-db
  namespace: banking-apps
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/name: banking-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: banking-service-db
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: banking/banking-service
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: banking/banking-service
        property: SPRING_DATASOURCE_PASSWORD
