apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - clustersecretstore-vault.yaml
  - externalsecret-postgresql.yaml
  - externalsecret-keycloak.yaml
  - externalsecret-banking-service.yaml
  - externalsecret-jenkins.yaml
