apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Spokes (east/west): ESO, Sail/OSSM 3, GitOps, RHSI, RHACS Sensor.
resources:
  - namespace-eso.yaml
  - subscription-eso.yaml
  - subscription-openshift-gitops.yaml
  - subscription-sail.yaml
  - subscription-skupper.yaml
  - namespace-rhacs.yaml
