apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Compatibility alias — same as operators-spoke.
resources:
  - namespace-rhbk.yaml
  - subscription-rhbk.yaml
  - namespace-eso.yaml
  - subscription-eso.yaml
  - subscription-openshift-gitops.yaml
  - subscription-sail.yaml
