apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: banking-service
  labels:
    app.kubernetes.io/part-of: banking-si-demo
spec:
  routingKey: banking-service
  port: 8080
  selector: app.kubernetes.io/name=banking-service
