apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-si-apps

resources:
  - site.yaml
  - connector.yaml
  - listener.yaml

commonLabels:
  app.kubernetes.io/part-of: banking-si-demo
