apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-bootstrap
  namespace: banking-conjur
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/component: conjur-config
