apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tpa-keycloak-admin
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/name: tpa-sso
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: conjur-backend
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: banking/tpa/keycloak-admin-username
    - secretKey: password
      remoteRef:
        key: banking/tpa/keycloak-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tpa-oidc-cli
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: banking-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: conjur-backend
  target:
    name: oidc-cli
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: banking/tpa/oidc-cli-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tpa-postgresql-credentials
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/name: tpa-postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: conjur-backend
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: db.host
      remoteRef:
        key: banking/tpa/postgresql-db-host
    - secretKey: db.name
      remoteRef:
        key: banking/tpa/postgresql-db-name
    - secretKey: db.user
      remoteRef:
        key: banking/tpa/postgresql-db-user
    - secretKey: db.password
      remoteRef:
        key: banking/tpa/postgresql-db-password
    - secretKey: db.port
      remoteRef:
        key: banking/tpa/postgresql-db-port
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tpa-postgresql-admin-credentials
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/name: tpa-postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: conjur-backend
  target:
    name: postgresql-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: db.host
      remoteRef:
        key: banking/tpa/postgresql-db-host
    - secretKey: db.name
      remoteRef:
        key: banking/tpa/postgresql-db-name
    - secretKey: db.user
      remoteRef:
        key: banking/tpa/postgresql-admin-user
    - secretKey: db.password
      remoteRef:
        key: banking/tpa/postgresql-admin-password
    - secretKey: db.port
      remoteRef:
        key: banking/tpa/postgresql-db-port

