apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: conjur
  namespace: banking-conjur
  labels:
    app.kubernetes.io/name: conjur
    app.kubernetes.io/part-of: banking-demo
spec:
  host: conjur.apps.cluster-k7kqp.k7kqp.sandbox3321.opentlc.com
  to:
    kind: Service
    name: conjur-oss
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
