apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.banking-db.svc.cluster.local:5432/banking
  # Bound by Spring Boot relaxed binding (resourceserver JWT)
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak-banking.apps.cluster-4487j.4487j.sandbox2772.opentlc.com/realms/banking
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://banking-keycloak-service.banking-idp.svc:8080/realms/banking/protocol/openid-connect/certs
