apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-devspaces

resources:
  - ../../base

commonLabels:
  cluster: east

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: env-config-devspaces
    envs:
      - env/devspaces.env

replacements:
  - source:
      kind: ConfigMap
      name: env-config-devspaces
      fieldPath: data.RHDA_BACKEND_URL
    targets:
      - select:
          group: org.eclipse.che
          version: v2
          kind: CheCluster
          name: devspaces
        fieldPaths:
          - spec.devEnvironments.defaultComponents.[name=universal-developer-image].container.env.[name=REDHAT_DEPENDENCY_ANALYTICS_EXHORT_BACKEND_URL].value
  - source:
      kind: ConfigMap
      name: env-config-devspaces
      fieldPath: data.TPA_URL
    targets:
      - select:
          group: org.eclipse.che
          version: v2
          kind: CheCluster
          name: devspaces
        fieldPaths:
          - spec.devEnvironments.defaultComponents.[name=universal-developer-image].container.env.[name=TPA_URL].value
