apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conjur
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/demo-spring.git
    targetRevision: main
    path: gitops/components/conjur
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-conjur
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: image.openshift.io
      kind: ImageStream
      jqPathExpressions:
        - .status
        - .metadata.annotations
    - group: ""
      kind: PersistentVolumeClaim
      jqPathExpressions:
        - .status
        - .spec.volumeName
        - .metadata.annotations
    - group: ""
      kind: Secret
      jqPathExpressions:
        - .metadata.annotations
        - .metadata.labels
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.metadata.annotations
        - .metadata.annotations
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.metadata.annotations
        - .metadata.annotations

