apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-banners
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: http://gitea-http.banking-git.svc:3000/banking/demo-spring.git
    targetRevision: main
    path: gitops/components/console-banners
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
