apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/demo-spring.git
    targetRevision: main
    path: gitops/components/devspaces/overlays/acm
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-devspaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    # Operator mutates annotations / defaults after apply.
    - group: org.eclipse.che
      kind: CheCluster
      jqPathExpressions:
        - .metadata.annotations
        - .status
