apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-ns
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/demo-spring.git
    targetRevision: main
    path: gitops/components/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: oci://docker.gitea.com/charts/gitea
      chart: gitea
      targetRevision: 12.7.0
      helm:
        releaseName: gitea
        valueFiles:
          - $values/gitops/components/gitea/helm-values.yaml
    - repoURL: https://github.com/panchoraposo/demo-spring.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
