apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-multicluster
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/demo-spring.git
    targetRevision: main
    path: gitops/components/kiali-multicluster
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
