apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: banking-db
  labels:
    app.kubernetes.io/name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
