apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openshift-default
  labels:
    app.kubernetes.io/part-of: banking-si-demo
  annotations:
    unsupported.do-not-use.openshift.io/ossm-channel: stable-3.4
    unsupported.do-not-use.openshift.io/ossm-version: servicemeshoperator3.v3.4.0
    unsupported.do-not-use.openshift.io/istio-version: v1.28-latest
spec:
  controllerName: openshift.io/gateway-controller/v1
