apiVersion: keda.sh/v1alpha1
kind: KedaController
metadata:
  name: keda
  namespace: openshift-keda
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/component: custom-metrics-autoscaler
spec:
  watchNamespace: ""
  operator:
    logLevel: info
    logEncoder: console
  metricsServer:
    logLevel: "0"
