apiVersion: v1
kind: Namespace
metadata:
  name: openshift-rhtas-operator
  labels:
    app.kubernetes.io/part-of: banking-demo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhtas-operator
  namespace: openshift-rhtas-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtas-operator
  namespace: openshift-rhtas-operator
  labels:
    app.kubernetes.io/part-of: banking-demo
spec:
  channel: stable
  name: rhtas-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
