apiVersion: v1
kind: Namespace
metadata:
  name: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: banking-demo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhtpa-operator
  namespace: trusted-profile-analyzer
spec:
  targetNamespaces:
    - trusted-profile-analyzer
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtpa-operator
  namespace: trusted-profile-analyzer
  labels:
    app.kubernetes.io/part-of: banking-demo
spec:
  channel: stable
  name: rhtpa-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
