apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
  labels:
    app.kubernetes.io/part-of: banking-demo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator
  namespace: quay-enterprise
spec:
  targetNamespaces:
    - quay-enterprise
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-enterprise
  labels:
    app.kubernetes.io/part-of: banking-demo
spec:
  channel: stable-3.14
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
