apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: banking-service
  namespace: banking-apps
  labels:
    app.kubernetes.io/name: banking-service
    app.kubernetes.io/part-of: banking-demo
spec:
  lookupPolicy:
    local: true
