apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rolebinding.yaml
  - buildconfig-pipeline.yaml
  - buildconfig-banking-service.yaml
  - buildconfig-api-gateway.yaml
