apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: platform.stackrox.io
      version: v1alpha1
      kind: SecuredCluster
      name: stackrox-secured-cluster-services
    patch: |-
      - op: replace
        path: /spec/clusterName
        value: east
      - op: replace
        path: /spec/centralEndpoint
        # acm Central Route (passthrough TLS). Updated by bootstrap / configure_environment.
        value: central-stackrox.apps.cluster-k7kqp.k7kqp.sandbox3321.opentlc.com:443
