apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: sailoperator.io
      version: v1
      kind: Istio
      name: default
    patch: |-
      - op: replace
        path: /spec/values/global/multiCluster/clusterName
        value: east
      - op: replace
        path: /spec/values/global/network
        value: network1
  - target:
      group: sailoperator.io
      version: v1
      kind: ZTunnel
      name: default
    patch: |-
      - op: replace
        path: /spec/values/ztunnel/multiCluster/clusterName
        value: east

commonLabels:
  cluster: east
