apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: sailoperator.io
      version: v1
      kind: Istio
      name: default
    patch: |-
      - op: replace
        path: /spec/values/global/multiCluster/clusterName
        value: west
      - op: replace
        path: /spec/values/global/network
        value: network2
  - target:
      group: sailoperator.io
      version: v1
      kind: ZTunnel
      name: default
    patch: |-
      - op: replace
        path: /spec/values/ztunnel/multiCluster/clusterName
        value: west
  - target:
      kind: Namespace
      name: istio-system
    patch: |-
      - op: replace
        path: /metadata/labels/topology.istio.io~1network
        value: network2
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: istio-eastwestgateway
    patch: |-
      - op: replace
        path: /metadata/labels/topology.istio.io~1network
        value: network2

commonLabels:
  cluster: west
