apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: banking-db
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: conjur-backend
  target:
    name: postgresql-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        database-name: "{{ .database_name }}"
        database-user: "{{ .database_user }}"
        database-password: "{{ .database_password }}"
        jdbc-url: "{{ .jdbc_url }}"
  data:
    - secretKey: database_name
      remoteRef:
        key: banking/postgresql/database-name
    - secretKey: database_user
      remoteRef:
        key: banking/postgresql/database-user
    - secretKey: database_password
      remoteRef:
        key: banking/postgresql/database-password
    - secretKey: jdbc_url
      remoteRef:
        key: banking/postgresql/jdbc-url

