apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - scc-privileged.yaml
  - istiocni.yaml
  - istio.yaml
  - ztunnel.yaml
  - eastwest-gateway.yaml
  - waypoint-banking-service.yaml
  - destinationrule-banking-service.yaml
  - networkpolicy-allow-kubelet-probes.yaml
