apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-workload-monitoring
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: west
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/demo-spring.git
    targetRevision: main
    path: gitops/components/monitoring-user-workload
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

