apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  BANKING_SERVICE_URI: http://banking-service.banking-apps.svc.cluster.local:8080
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak-banking.apps.cluster-4487j.4487j.sandbox2772.opentlc.com/realms/banking
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://banking-keycloak-service.banking-idp.svc:8080/realms/banking/protocol/openid-connect/certs
