# Hub ClusterSecretStore — Conjur on the same cluster (acm).
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: conjur-backend
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: acm
spec:
  provider:
    conjur:
      url: https://conjur-oss.banking-conjur.svc
      caProvider:
        type: Secret
        name: conjur-oss-conjur-ssl-ca-cert
        key: tls.crt
        namespace: banking-conjur
      auth:
        apikey:
          account: banking
          userRef:
            name: conjur-creds
            namespace: external-secrets
            key: hostid
          apiKeyRef:
            name: conjur-creds
            namespace: external-secrets
            key: apikey
