apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: banking-ci
  labels:
    app.kubernetes.io/part-of: banking-demo
    app.kubernetes.io/name: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: conjur-backend
  target:
    name: jenkins-admin
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: banking/jenkins/jenkins-admin-user
    - secretKey: jenkins-admin-password
      remoteRef:
        key: banking/jenkins/jenkins-admin-password
