apiVersion: v1
kind: Namespace
metadata:
  name: banking-apps
  labels:
    app.kubernetes.io/part-of: banking-demo
    cluster: west
    istio.io/dataplane-mode: ambient
    istio-discovery: enabled
